# Site settings
title: Jordy de Koning
description: Passionate Developer | Blockchain Enthusiast | Security Auditor
author: Jordy de Koning
email: hello@jordydekoning.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jordydekoning.com" # the base hostname & protocol for your site
logo: /assets/images/og-image.png
image: /assets/images/og-image.png

# Social media
twitter_username: developerjordy
github_username: JordyKingz
linkedin_username: jordydekoning
telegram_username: developerjordy

# Build settings
markdown: kramdown
theme: minima

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Malware lab configuration
malware:
  presign_endpoint: /api/presign
  samples_feed: https://malware-drop.jordydekoning.com/manifest.json
  bucket_public_url: https://malware.dropbox.ams3.digitaloceanspaces.com
  bearer_token: OGZkNGM4MGEtNTA4Yi00YWM3LWI2OGYtZTg3MjVlNmM5YzAyOjVyNHR1UmZ6UkV6eXZZUjRNcVJvdVB3QndaUjhmMmtYV1REMXpoWE1aeG1rcHp4NmFaZUtyRXRKNk1rb3Voa00=

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
